version: 2
jobs:
  build:
    working_directory: /go/src/github.com/paulnguyen/circleci
    docker:
      - image: circleci/golang:1.8
    environment:
      GOPATH: "${HOME}/.go_workspace:/usr/local/go_workspace:${HOME}/.go_project"     
    steps:
      - checkout
      - run: ls .
      - run: echo $GOPATH
      - run: go test tests
      - run: go build gumball
      - run:
          name: Start service
          command: ./gumball
          background: true
      - run:
          name: Validate service is working
          command: |
            sleep 5
            curl --retry 10 --retry-delay 1 -X GET http://localhost:3000/ping


    