version: 2
jobs:
  build:
    working_directory: /go/src/github.com/paulnguyen/circleci
    docker:
      - image: circleci/golang:1.8
    environment:
      GOPATH: /go/src/github.com/paulnguyen/circleci     
    steps:
      - checkout
      - run: go get net/http
      - run: go get encoding/json
      - run: go get github.com/codegangsta/negroni
      - run: go get github.com/gorilla/mux
      - run: go get github.com/satori/go.uuid
      - run: go get github.com/unrolled/render
      - run: echo $GOPATH
      - run: go test tests
      - run: go build gumball
      - run:
          name: Start service
          command: ./gumball
          background: true
      - run:
          name: Validate service is working
          command: |
            sleep 5
            curl --retry 10 --retry-delay 1 -X GET http://localhost:3000/ping
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t paulnguyen/circleci:beta .
      - run: docker push paulnguyen/circleci:beta


    